packages:
  - "packages/*"
  - "packages/providers/*"
  - "packages/vectorstores/*"
  - "examples/*"
  - "apps/*"
allowBuilds:
  '@parcel/watcher': false
  cpu-features: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  protobufjs: true
  ssh2: true
