packages:
  - "packages/*"
  - "packages/providers/*"
  - "packages/vectorstores/*"
  - "examples/*"
allowBuilds:
  cpu-features: true
  esbuild: true
  msgpackr-extract: true
  nx: true
  protobufjs: true
  ssh2: true
