import { defineConfig } from 'vite';
import type { Plugin } from 'vite';
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { DOC_PAGES, docPath } from './src/docs/nav.ts';
import { buildSearchIndex } from './src/docs/search-core.ts';
import type { IndexApiPackage } from './src/docs/search-core.ts';

const repo = resolve(import.meta.dirname, '../..');
const docs = join(repo, 'docs');
const read = (file: string): string => readFileSync(file, 'utf8').replace(/\r\n/g, '\n');

/** Fails the build when a relative Markdown link in the published docs points to a missing file. */
function checkLinks(): Plugin {
  return {
    name: 'gix-docs-link-check',
    buildStart() {
      const dirs = ['guides', 'production', 'reference', 'migrations'].map((dir) => join(docs, dir)).filter(existsSync);
      const files = [...dirs.flatMap((dir) => readdirSync(dir).filter((file) => file.endsWith('.md')).map((file) => join(dir, file))), ...['VERSIONING.md', 'RELEASING.md', 'ARCHITECTURE_OVERVIEW.md', 'ROADMAP.md'].map((file) => join(docs, file)).filter(existsSync)];
      const broken: string[] = [];
      for (const file of files) {
        for (const match of read(file).matchAll(/\]\(([^)\s]+)\)/g)) {
          const href = match[1] ?? '';
          if (/^[a-z]+:/i.test(href) || href.startsWith('#')) continue;
          const target = resolve(dirname(file), href.split('#')[0] ?? '');
          if (!existsSync(target)) broken.push(`${file.slice(docs.length + 1)} -> ${href}`);
        }
      }
      for (const page of DOC_PAGES) if (page.source && !existsSync(join(repo, page.source))) broken.push(`navigation -> ${page.source}`);
      if (broken.length > 0) this.error(`Broken documentation links:\n  ${broken.join('\n  ')}`);
    },
  };
}

const SITE_PAGES = [
  { url: '/', label: 'Home', group: 'Website', description: 'GIX AI Copilot SDK: build AI that understands your application.' },
  { url: '/enterprise', label: 'Enterprise security', group: 'Website', description: 'AI Action Firewall, approvals, audit, PII, multi-tenancy, usage controls.' },
  { url: '/examples', label: 'Examples', group: 'Website', description: 'Runnable React, Angular and Node examples filtered by capability.' },
];

/**
 * Build-time data as virtual modules, each emitted as its own lazily imported chunk:
 *   virtual:gix-search-index  the search index (pages, headings, API symbols, CLI commands)
 *   virtual:gix-api           docs/reference/api.json (generated by tools/api-reference.mjs)
 */
function buildData(): Plugin {
  const ids = { search: 'virtual:gix-search-index', api: 'virtual:gix-api' };
  const apiFile = join(docs, 'reference', 'api.json');
  return {
    name: 'gix-docs-data',
    resolveId(id) {
      return id === ids.search || id === ids.api ? `\0${id}` : undefined;
    },
    load(id) {
      if (id === `\0${ids.api}`) {
        this.addWatchFile(apiFile);
        return `export default ${read(apiFile)};`;
      }
      if (id !== `\0${ids.search}`) return undefined;
      this.addWatchFile(apiFile);
      const api = (JSON.parse(read(apiFile)) as { packages: IndexApiPackage[] }).packages;
      const pages = DOC_PAGES.map((page) => {
        if (page.source) this.addWatchFile(join(repo, page.source));
        return { url: page.slug === 'api' ? '/docs/api' : docPath(page.slug), label: page.label, group: page.section, description: page.description, markdown: page.source ? read(join(repo, page.source)) : undefined };
      });
      return `export default ${JSON.stringify(buildSearchIndex(pages, api, SITE_PAGES))};`;
    },
  };
}

/**
 * `vite preview` behaves like the production static host: /docs/tools serves the prerendered
 * web-dist/docs/tools/index.html, and unknown paths get 404.html with a 404 status.
 */
function prerenderedPreview(): Plugin {
  return {
    name: 'gix-prerendered-preview',
    configurePreviewServer(server) {
      const dist = resolve(import.meta.dirname, 'web-dist');
      server.middlewares.use((req, res, next) => {
        const path = decodeURIComponent((req.url ?? '/').split(/[?#]/)[0] ?? '/').replace(/\/+$/, '');
        if (/\.[a-z0-9]+$/i.test(path)) return next();
        const page = join(dist, path, 'index.html');
        if (existsSync(page)) {
          req.url = `${path}/index.html`;
          return next();
        }
        res.statusCode = 404;
        res.setHeader('content-type', 'text/html; charset=utf-8');
        res.end(readFileSync(join(dist, '404.html')));
      });
    },
  };
}

export default defineConfig({
  plugins: [checkLinks(), buildData(), prerenderedPreview()],
  base: '/',
  server: { host: '127.0.0.1', port: 5200, strictPort: true, fs: { allow: ['../..'] } },
  preview: { host: '127.0.0.1', port: 5200, strictPort: true },
  build: { outDir: 'web-dist', target: 'es2022', emptyOutDir: true },
  ssr: { noExternal: ['@fontsource-variable/inter', '@fontsource-variable/jetbrains-mono'] },
});
