/// <reference types="vite/client" />

/** Build-time search index (vite.config.ts); loaded lazily when search opens. */
declare module 'virtual:gix-search-index' {
  const entries: readonly unknown[];
  export default entries;
}

/** docs/reference/api.json (generated by tools/api-reference.mjs); loaded on API pages only. */
declare module 'virtual:gix-api' {
  const api: unknown;
  export default api;
}
