/** Small, deterministic source-text helpers shared by the generators. */

export const GENERATED_ROOT = '.gix';

export function header(generator: string, detail: string): string {
  return [
    `// Generated by GIX Developer Studio (${generator}). ${detail}`,
    '// Application plane: nothing in this file is active until your code imports and registers it.',
    '// Review it like any other code. Regenerating from the Studio shows a diff before overwriting.',
    '',
  ].join('\n');
}

export function slug(value: string): string {
  return (
    value
      .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
      .replace(/[^A-Za-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .toLowerCase() || 'generated'
  );
}

export function identifier(value: string): string {
  const words = value.split(/[^A-Za-z0-9]+/).filter(Boolean);
  const joined = words.map((word, index) => (index === 0 ? word.charAt(0).toLowerCase() + word.slice(1) : word.charAt(0).toUpperCase() + word.slice(1))).join('');
  return /^[A-Za-z_]/.test(joined) ? joined : `_${joined}`;
}

export function pascal(value: string): string {
  const id = identifier(value);
  return id.charAt(0).toUpperCase() + id.slice(1);
}

/** A string literal for generated source. JSON escaping is valid TypeScript. */
export const str = (value: string): string => JSON.stringify(value);

type JsonSchema = Readonly<Record<string, unknown>>;

function isSchema(value: unknown): value is JsonSchema {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/** Zod source for a JSON Schema fragment. Unknown shapes become `z.unknown()`, never `any`. */
export function zodFromJsonSchema(schema: unknown, depth = 0): string {
  if (!isSchema(schema) || depth > 6) return 'z.unknown()';
  const enumValues = schema['enum'];
  if (Array.isArray(enumValues) && enumValues.length > 0 && enumValues.every((value) => typeof value === 'string')) {
    return `z.enum([${(enumValues).map(str).join(', ')}])`;
  }
  const type = Array.isArray(schema['type']) ? (schema['type'] as unknown[]).find((value) => value !== 'null') : schema['type'];
  switch (type) {
    case 'string':
      return 'z.string()';
    case 'integer':
      return 'z.number().int()';
    case 'number':
      return 'z.number()';
    case 'boolean':
      return 'z.boolean()';
    case 'array':
      return `z.array(${zodFromJsonSchema(schema['items'], depth + 1)})`;
    case 'object':
    case undefined: {
      const properties = schema['properties'];
      if (!isSchema(properties)) return type === 'object' ? 'z.record(z.string(), z.unknown())' : 'z.unknown()';
      const required = new Set(Array.isArray(schema['required']) ? (schema['required'] as string[]) : []);
      const fields = Object.entries(properties).map(([name, value]) => `${/^[A-Za-z_$][\w$]*$/.test(name) ? name : str(name)}: ${zodFromJsonSchema(value, depth + 1)}${required.has(name) ? '' : '.optional()'}`);
      return `z.object({ ${fields.join(', ')} })`;
    }
    default:
      return 'z.unknown()';
  }
}

/** Zod source for a discovered TypeScript prop type text. `known` is false for a fallback. */
export function zodFromTypeText(type: string): { readonly code: string; readonly known: boolean } {
  const text = type.trim().replace(/^readonly\s+/, '');
  if (text === 'string') return { code: 'z.string()', known: true };
  if (text === 'number') return { code: 'z.number()', known: true };
  if (text === 'boolean') return { code: 'z.boolean()', known: true };
  if (text === 'Date') return { code: 'z.string().describe("ISO 8601 date")', known: true };
  const array = /^(?:Array<(\w+)>|ReadonlyArray<(\w+)>|(\w+)\[\])$/.exec(text);
  if (array) {
    const inner = zodFromTypeText(array[1] ?? array[2] ?? array[3] ?? 'unknown');
    return { code: `z.array(${inner.code})`, known: inner.known };
  }
  const literals = text.split('|').map((part) => part.trim());
  if (literals.length > 0 && literals.every((part) => /^(['"]).*\1$/.test(part))) {
    return { code: `z.enum([${literals.map((part) => str(part.slice(1, -1))).join(', ')}])`, known: true };
  }
  return { code: 'z.unknown()', known: false };
}
