import type { DevToolsDemo } from './backend.js';

const chat = (text: string) => ({ model: { provider: 'chat-model', model: 'test-model' }, messages: [{ role: 'user', content: [{ type: 'text', text }] }] });

async function waitForPendingApproval(demo: DevToolsDemo): Promise<string> {
  for (let attempt = 0; attempt < 200; attempt += 1) {
    const response = await demo.app.inject({ method: 'GET', url: '/approvals', headers: { authorization: 'Bearer supervisor' } });
    const pending = response.json<{ approvals: { approvalId: string; status: string }[] }>().approvals.find((approval) => approval.status === 'pending');
    if (pending) return pending.approvalId;
    await new Promise((resolve) => setTimeout(resolve, 10));
  }
  throw new Error('No approval was requested.');
}

export interface ScenarioResult {
  readonly chatBody: string;
  readonly deniedBody: string;
  readonly agentStatus: string;
  readonly workflowStatus: string;
}

/**
 * One realistic session, driven over the app's real HTTP API (Section 206, 208): a chat that
 * reads an application, renders a generative-UI card and asks to reassign it (supervisor
 * approval, decided by a human over HTTP); a chat that attempts a forbidden delete; a
 * multi-agent question fanned out to three specialists (RAG + memory); a workflow that pauses
 * for approval and resumes; a context resolution with a restricted item; and shared-state
 * patches including a stale-revision conflict. The resulting trace is generated by execution,
 * never hand-written (Section 208).
 */
export async function runScenario(demo: DevToolsDemo): Promise<ScenarioResult> {
  const officerChat = demo.app.inject({ method: 'POST', url: '/runs', headers: { authorization: 'Bearer officer' }, payload: chat('Show APP-1024 as a card, then reassign it to Officer B.') });
  const approvalId = await waitForPendingApproval(demo);
  const approved = await demo.app.inject({ method: 'POST', url: `/approvals/${approvalId}/approve`, headers: { authorization: 'Bearer supervisor' }, payload: { comment: 'Workload balancing' } });
  if (approved.statusCode !== 200) throw new Error(`Approval failed: ${approved.body}`);
  const chatBody = (await officerChat).body;

  const deniedBody = (await demo.app.inject({ method: 'POST', url: '/runs', headers: { authorization: 'Bearer applicant' }, payload: chat('Delete APP-1024.') })).body;

  const agent = await demo.app.inject({ method: 'POST', url: '/agents/ask', headers: { authorization: 'Bearer applicant' }, payload: { message: 'Check APP-1024, my payment, and the approval policy.' } });

  const started = (await demo.app.inject({ method: 'POST', url: '/workflows/reassignment', headers: { authorization: 'Bearer officer' }, payload: { id: 'APP-1024' } })).json<{ workflowRunId: string; approvalId: string }>();
  const resumed = await demo.app.inject({ method: 'POST', url: `/workflows/${started.workflowRunId}/approvals/${started.approvalId}/approve`, headers: { authorization: 'Bearer supervisor' } });

  await demo.app.inject({ method: 'POST', url: '/context/resolve' });
  await demo.app.inject({ method: 'POST', url: '/state/filters', payload: { status: 'open', baseRevision: 0 } });
  await demo.app.inject({ method: 'POST', url: '/state/filters', payload: { status: 'closed', baseRevision: 0 } }); // stale -> conflict

  return {
    chatBody,
    deniedBody,
    agentStatus: agent.json<{ status: string }>().status,
    workflowStatus: resumed.json<{ status: string }>().status,
  };
}
